export const CATEGORY_ICONS = [
  { icon: "🛒", label: "Products" },
  { icon: "🍔", label: "Food" },
  { icon: "☕", label: "Coffee" },
  { icon: "🍕", label: "Fast Food" },
  { icon: "🏠", label: "Home" },
  { icon: "💡", label: "Utilities" },
  { icon: "📱", label: "Subscriptions" },
  { icon: "🚕", label: "Transport" },
  { icon: "⛽", label: "Fuel" },
  { icon: "🚗", label: "Car" },
  { icon: "🚌", label: "Public Transport" },
  { icon: "🏥", label: "Health" },
  { icon: "💊", label: "Medicine" },
  { icon: "💪", label: "Fitness" },
  { icon: "🎮", label: "Entertainment" },
  { icon: "🎬", label: "Movies" },
  { icon: "🎵", label: "Music" },
  { icon: "🎁", label: "Gifts" },
  { icon: "👕", label: "Clothes" },
  { icon: "👟", label: "Shopping" },
  { icon: "🎓", label: "Education" },
  { icon: "📚", label: "Books" },
  { icon: "✈️", label: "Travel" },
  { icon: "🏖", label: "Vacation" },
  { icon: "🐶", label: "Pets" },
  { icon: "👶", label: "Kids" },
  { icon: "🧾", label: "Bills" },
  { icon: "🔧", label: "Repairs" },
  { icon: "🪑", label: "Furniture" },
  { icon: "🍺", label: "Bar" },
  { icon: "🍷", label: "Alcohol" },
  { icon: "🛍", label: "Marketplace" },
  { icon: "📦", label: "Delivery" },
  { icon: "🧹", label: "Cleaning" },
  { icon: "🔒", label: "Insurance" },
  { icon: "⚡", label: "Electricity" },
  { icon: "🌐", label: "Internet" },
  { icon: "📞", label: "Mobile" },
]